name: etcd
version: 0.0.1
appVersion: 3.3.8
description: etcd is a distributed key value store that provides a reliable way to store data across a cluster of machines
keywords:
- etcd
- cluster
- database
- cache
- key-value
home: https://coreos.com/etcd/
sources:
- https://github.com/bitnami/bitnami-docker-etcd
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/etcd/img/etcd-stack-110x117.png
